### ISSUE TITLE
npm test fails on windows

### ISSUE THREAD

**Issue by broerse** [kellyselden/git-diff-apply#167]
When I clone the project and run `npm test` I get the failing test:

```
  22 passing (1m)
  1 failing

  1) Acceptance - git-diff-apply
       handles conflicts:

      AssertionError: expected { Object (added-changed.txt, added-unchanged.txt, ...) } to deeply equal { Object (added-changed.txt, added-unchanged.txt, ...) }
      + expected - actual

       {
         "added-changed.txt": "added-v3\r\n"
         "added-unchanged.txt": "added-unchanged\r\n"
      -  "present-added-changed.txt": "present-added-v3\n"
      +  "present-added-changed.txt": "present-added-v3\r\n"
         "present-added-unchanged.txt": "present-added-unchanged\r\n"
         "present-changed.txt": "present-v3\r\n"
         "present-unchanged.txt": "present-unchanged\r\n"
       }

      at Proxy.assertEqual (node_modules\chai\lib\chai\core\assertions.js:1020:19)
      at Proxy.methodWrapper (node_modules\chai\lib\chai\utils\addMethod.js:57:25)
      at fixtureCompare (node_modules\git-fixtures\src\index.js:203:28)
      at fixtureCompare (test\acceptance\git-diff-apply-test.js:58:5)
      at merge.then (test\acceptance\git-diff-apply-test.js:72:7)
      at <anonymous>
      at runMicrotasksCallback (internal/process/next_tick.js:121:5)
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickCallback (internal/process/next_tick.js:180:9)



npm ERR! Test failed.  See above for more details.
```

**Comment by kellyselden** [comment]
Tests pass for me on Windows. I'm using cmd.exe as an admin. Are you using a different shell, or do you having anything in your global git config that would affect line endings?

**Comment by broerse** [comment]
I am using cmd as admin with Git configured the tread line endings AS IS.

**Comment by kellyselden** [comment]
There might be an issue somewhere, but I don't know how to help. It is working for me and on Appveyor CI.
